services:
  app:
    build: .
    restart: always
    environment:
      - DB_HOST=mongo
      - APP_PORT=5051
    networks:
      - host
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo:/data/db

volumes:
  mongo: null
