services:
  app:
    build: .
    restart: always
    environment:
      DB_HOST: mongo
      APP_PORT: 5051
      APPS_DIR: /root/apps
    network_mode: host
    volumes:
      - /root/apps:/root/apps
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo:/data/db

volumes:
  mongo: null