services:
  app:
    build: .
    restart: always
    environment:
      - DB_HOST=mongo
      - APP_PORT=5051
    ports:
      - 5051:5051
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo:/data/db

volumes:
  mongo: null
